# Site settings
title:       James Wigger
email:       james.s.wigger@gmail.com
author:      James Wigger
description: "The personal portfolio, blog and photo-blog of Lincoln based PHP &amp; Front-End developer, James Wigger."
baseurl:     ""
url:         "http://jameswigger.co.uk"

# Google analytics
google_analytics: UA-2001719-4

# Optional features
show_related_posts: false
show_post_footers:  false

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: jamesyps
stackoverflow_id:
twitter_username: jamesyps
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
not_paginated_categories:
  - portfolio
sass:
  style: :compressed
  compressed: true
gems:
  - jekyll-sitemap
